[project]
authors = ["Dan Allan <dallan@bnl.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "interactive-tutorial-demo"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
build = { cmd = [
    "sphinx-build",
    "docs",  # source directory
    "build/html",  # target directory
    "-n",  # warn about missing references
    "-W",  # any warnings fail the build
    "-T",  # show tracebacks
    "--keep-going",  # do not stop on error
] }
clean = "rm -rf build/*"

[dependencies]
python = ">=3.12.5,<4"
matplotlib-base = ">=3.9.2,<4"
ipympl = ">=0.9.4,<0.10"
jupyterlab = ">=4.2.5,<5"
jupyterlab-myst = ">=2.4.2,<3"
pydata-sphinx-theme = ">=0.15.4,<0.16"
sphinxcontrib-serializinghtml = ">=1.1.10,<2"
tiled = ">=0.1.0b32,<0.2"
bluesky = ">=1.14.2,<2"

[pypi-dependencies]
sphinx = ">=8.0.2, <9"
myst-nb = ">=1.1.1, <2"
jupytext = ">=1.16.4, <2"
sphinx-copybutton = ">=0.5.2, <0.6"

[feature.jupyterlite.dependencies]
jupyterlab = "~=4.2.4"
jupyterlite-core = "==0.4.0"
jupyterlite-pyodide-kernel = "==0.4.1"
notebook = "~=7.2.1"

[environments]
jupyterlite = ["jupyterlite"]
