[project]
authors = ["Dan Allan <dallan@bnl.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "interactive-tutorial-demo"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
build = { cmd = [
    "sphinx-build",
    "docs",  # source directory
    "build/html",  # target directory
    "-n",  # warn about missing references
    "-W",  # any warnings fail the build
    "-T",  # show tracebacks
    "--keep-going",  # do not stop on error
] }
clean = "rm -rf build/*"

[dependencies]
python = ">=3.11.10,<3.12"
matplotlib-base = ">=3.9.2,<4"
ipympl = ">=0.9.4,<0.10"
jupyterlab = ">=4.2.5,<5"
jupyterlab-myst = ">=2.4.2,<3"
pydata-sphinx-theme = ">=0.15.4,<0.16"
sphinxcontrib-serializinghtml = ">=1.1.10,<2"
numpy = "<2.0.0"
aioca = ">=1.7,<2"
pytest = ">=8.3.4,<9"

[pypi-dependencies]
sphinx = ">=8.0.2, <9"
myst-nb = ">=1.1.1, <2"
jupytext = ">=1.16.4, <2"
sphinx-copybutton = ">=0.5.2, <0.6"
bluesky = { git = "https://github.com/bluesky/bluesky.git", rev = "51bfc0339a75d8ae1f6e697dba51f524322d34ef"}
ophyd-async = { version = ">=0.6.0", extras=["sim"]}
ophyd = ">=1.9.0, <2"
tiled = { version =">=0.1.0b12,<0.2", extras=["all"]}

[feature.jupyterlite.dependencies]
jupyterlab = "~=4.2.4"
jupyterlite-core = "==0.4.0"
jupyterlite-pyodide-kernel = "==0.4.1"
notebook = "~=7.2.1"

[environments]
jupyterlite = ["jupyterlite"]
