on:
  workflow_call:
    inputs:
      nox:
        type: string
        description: What to run under nox
        required: true

jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Run nox
        run: nox -e ${{ inputs.nox }}
