---
name: Test notebooks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  test:
    name: Test all executable examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1

      - name: Test all files
        run: pixi run ./test.sh --all
