name: GitHub Pages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
      - 13-docs-cicd

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install python packages
        uses: ./.github/actions/install_requirements
      - name: Build
        run: nox -s docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_brash: gh-pages