name: GitHub Pages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: nox -s docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_brash: gh-pages